# Jekyll
server: true
auto: true
markdown: rdiscount
pygments: true
permalink: /:title.html

# Conference info
conf:
  name: "d3.unconf"
  description: "Conference description"
  date: "March 29, 2014"
  price: "$100"
  address: "GitHub HQ, 88 Colin P Kelly Jr St, San Francisco, CA 94107"
  venue: "GitHub HQ"
  city: "San Francisco"

# Site info
site:
  url: "http://visfest.com/d3unconf"
  favicon: "http://braziljs.org/favicon.ico"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "/img/IMG_1383.jpg"
    facebook: "http://braziljs.org/img/fb-share.jpg"

# Active sections on the website
sections:
  about: true
  mailing_list: true
  location: true
  faq: true
  speakers: true
  schedule: true
  sponsors: false 
  partners: true
  contact: false
  code_of_conduct: true 

# The entire schedule
schedule:
  -
    name: "Registration / Breakfast"
    time: "9:00 AM"
  -
    name: "Irene Ros"
    photo: "/img/keynote.jpg"
    bio: '<a href="">Irene</a> is a core developer for <a href="">The Miso Project</a>, a framework for interactive storytelling with data. She organizes the Boston conference <a href="">OpenVisConf</a> and is a Senior Developer at <a href="">Bocoup.</a>'
    company: "Boucoup"
    twitter: "ireneros"
    presentation:
      title: "Opening Keynote"
      time: "10:00 AM"
  -
    name: "2x5 Sessions"
    time: "10:30 AM"
    description: "Converge on final schedule; first sessions"
  -
    name: "Lunch"
    time: "12:30 PM"
  -
    name: "2x5 Sessions"
    time: "1:30 PM"
    description: "Your ideas here"
  -
    name: "Break"
    time: "3:30 PM"
  -
    name: "2x5 Sessions"
    time: "4:00 PM"
    description: "Your ideas here"
  -
    name: "Dinner"
    time: "6:00 PM"

# List of Partners
partners:
  -
    name: "Bay Area d3 Meetup"
    logo: "/img/d3bayarea.jpg"
    url: "http://www.meetup.com/Bay-Area-d3-User-Group"
